select
    ACCOUNT_ID,
    LAST_ACCOUNT_MEETING_DATE,
    ACTIVE_USE_CASES,
    IN_PURSUIT_USE_CASES,
    IN_IMPLEMENTATION_USE_CASES,
    HIGH_RISK_USE_CASES,
    ANNUAL_RUN_RATE_L30D,
    ANNUAL_RUN_RATE_L90D,
    RUN_RATE_ACCELERATION_PCT,
    CONSUMPTION_RISK

from {{ source('se_reporting', 'account_base_metrics') }}
