select
    ACCOUNT_ID,
    ASSESSMENT_TIER,
    CONSUMPTION_CONTEXT,
    GROWTH_TIER,
    USE_CASE_HEALTH_CONTEXT,
    SE_ENGAGEMENT_CONTEXT,
    CONSUMPTION_PERFORMANCE_SCORE,
    CONSUMPTION_RISK,
    ACCOUNT_RISK,
    ACCOUNT_TIER,
    VOLUME_TIER,
    STABILITY_TIER,
    ANNUAL_RUN_RATE_L30D,
    ANNUAL_RUN_RATE_L90D,
    RUN_RATE_ACCELERATION_PCT,
    ACTIVE_PRODUCT_CATEGORY_COUNT,
    LAST_ACCOUNT_MEETING_DATE as IND_LAST_MEETING_DATE,
    DISTRICT_NAME

from {{ source('se_reporting', 'account_business_indicators') }}
